---
title: "Overall Run for NN benchmarking"
author: "GSoC 2019, GSoC 2020 members"
date: "8/2/2020"
output: html_document
---
```{r child = '(x)NNbenchmark-2020-BNN.Rmd'}
```

```{r child = '(x)NNbenchmark-2020-GMDHreg.Rmd'}
```

```{r child = '(x)NNbenchmark-2020-TrafficBDE.Rmd'}
```

```{r child = '(x)NNbenchmark-2020-yager.Rmd'}
```

```{r child = 'NNbenchmark-2020-AMORE.Rmd'}
```

```{r child = 'NNbenchmark-2020-ANN2.Rmd'}
```

```{r child = 'NNbenchmark-2020-automl.Rmd'}
```

```{r child = 'NNbenchmark-2020-brnn.Rmd'}
```

```{r child = 'NNbenchmark-2020-CaDENCE.Rmd'}
```

```{r child = 'NNbenchmark-2020-caret.Rmd'}
```

```{r child = 'NNbenchmark-2020-deepdive.Rmd'}
```

```{r child = 'NNbenchmark-2020-deepnet.Rmd'}
```

```{r child = 'NNbenchmark-2020-elmNNRcpp.Rmd'}
```

```{r child = 'NNbenchmark-2020-ELMR.Rmd'}
```

```{r child = 'NNbenchmark-2020-EnsembleBase.Rmd'}
```

```{r child = 'NNbenchmark-2020-h2o.Rmd'}
```

```{r child = 'NNbenchmark-2020-keras.Rmd'}
```

```{r child = 'NNbenchmark-2020-MachineShop.Rmd'}
```

```{r child = 'NNbenchmark-2020-minpack.lm.Rmd'}
```

```{r child = 'NNbenchmark-2020-monmlp.Rmd'}
```

```{r child = 'NNbenchmark-2020-neuralnet.Rmd'}
```

```{r child = 'NNbenchmark-2020-nlsr.Rmd'}
```

```{r child = 'NNbenchmark-2020-nnet.Rmd'}
```

```{r child = 'NNbenchmark-2020-qrnn.Rmd'}
```

```{r child = 'NNbenchmark-2020-radiant.model.Rmd'}
```

```{r child = 'NNbenchmark-2020-rminer.Rmd'}
```

```{r child = 'NNbenchmark-2020-RSNNS.Rmd'}
```

```{r child = 'NNbenchmark-2020-snnR.Rmd'}
```

```{r child = 'NNbenchmark-2020-traineR.Rmd'}
```

```{r child = 'NNbenchmark-2020-validann.Rmd'}
```