---
title: "Top Packages with Large Datasets"
author: "All members of GSoC 2019 & 2020"
date: "2020/10/16"
output:
    html_document:
        toc: true
        toc_float: true
        number_sections: true
---

# Setup 

```{r setup, message=FALSE, warning=FALSE}
library(NNbenchmark)
library(kableExtra)
library(knitr)
options(scipen = 999)
```

# Dataset to test

```{r}
NNdataSummary(NNbigdatasets)
ht(bWoodN1)
```

Check result

```{r}
if(dir.exists("D:/GSoC2020/Results/2020run05/"))
{  
  odir <- "D:/GSoC2020/Results/2020run05/"
}else if(dir.exists("~/Documents/recherche-enseignement/code/R/NNbenchmark-project/NNbenchmarkTemplates/results_2020_gsoc2020"))
{  
  odir <- "~/Documents/recherche-enseignement/code/R/NNbenchmark-project/NNbenchmarkTemplates/results_2020_gsoc2020"
}else
  odir <- "."

f2test <- c(
  paste0(odir, "/","bWoodN1_MachineShop_fit_none.RData"),
  paste0(odir, "/","bWoodN1_validann_ann_BFGS.RData"),
  paste0(odir, "/","bWoodN1_nnet_nnet_none.RData"),
  paste0(odir, "/","bWoodN1_rminer_fit_none.RData"),
  paste0(odir, "/","bWoodN1_nlsr_nlxb_none.RData"))

stopifnot(all(file.exists(f2test)))
```


# Graphics

## Plot functions 
```{r}

woodfunc <- function(x, j)
{
  f0 <- function(x) 5*sin(2*pi*x)
  f1 <- function(x) exp(3*x)-7
  f2 <- function(x) 
    0.5*x^11*(10*(1 - x))^6 - 10*(10*x)^3*(1 - x)^10
  f3 <- function(x)
    15*exp(-5*abs(x-1/2))-6
  f4 <- function(x)
    2-(x <= 1/3)*(6*x)^3 - (x >= 2/3)*(6-6*x)^3 - (x > 1/3 & x < 2/3)*(8+2*sin(9*(x-1/3)*pi))
  eta <- 1 + f0(x)+f1(x)+f2(x)+f3(x)+f4(x)+f0(x)
  meta <- mean(eta)
  if(missing(j))
    return(identity(eta))
  etaj <- do.call(paste0("f", j %% 5), list(x))
  etaj+meta
}


controlplot <- function(data, plot.nr, plot.nc, plot.mar=c(4,4,2,1), plot.nobs=1000, 
                        var2round, lwd, theo=TRUE, dolegend=TRUE, ...)
{
  if(var2round)
  {
    par(mfrow=c(plot.nr,plot.nc), mar=plot.mar)
    for(j in 1:(plot.nr*plot.nc))
    {
      Vjb <- round(data[,paste0("x",j)], 2)
      plot(sort(unique(Vjb)), tapply(data$y, Vjb, mean), 
           xlab=paste0("rounded variable ", j), ylab=expression(bar(y)), ...)
      lines(sort(unique(Vjb)), tapply(data$ypred, Vjb, mean), col="red", lwd=lwd)
      curve(woodfunc(x, j), add=TRUE, col="green", lwd=lwd)
      if(dolegend)
      {
        if((j >= 1 && j <= 3) || j == 6) 
          legend("topleft", lty=1, col=c("black","red","green"), 
                 leg=c("emp.", "pred.", "theo."), box.col = NA)
        if(j >= 4 && j <= 5) 
          legend("bottomleft", lty=1, col=c("black","red","green"), 
                 leg=c("emp.", "pred.", "theo."), box.col = NA)
      }
    }
    
  }else
  {
    n <- min(plot.nobs, NROW(data)) 
    par(mfrow=c(plot.nr,plot.nc), mar=plot.mar)
    for(j in 1:(plot.nr*plot.nc))
    {
      plot(data[1:n,paste0("x",j)], data$y[1:n], 
           xlab=paste0("original variable ", j), ylab="y",...)
      points(data[1:n,paste0("x",j)], data$ypred[1:n], col="red")
      if(dolegend)
      {
        if((j >= 1 && j <= 3) || j == 6) 
          legend("topleft", pch=1, col=c("black","red","green"), 
                 leg=c("emp.", "pred.", "theo."), box.col = NA)
        if(j >= 4 && j <= 5) 
          legend("bottomleft", pch=1, col=c("black","red","green"), 
                 leg=c("emp.", "pred.", "theo."), box.col = NA)
      }
    }
  }
  
}
```


## Graphics

```{r}


#graphical param
mypch <- 1 #see ?points
mylwd <- 1.25

load(paste0(odir, "/","bWoodN1_MachineShop_fit_none.RData"))
idxmin <- which.min(allsummary["RMSE", ])
cname <- names(idxmin)
bWoodN1pred <- cbind.data.frame(bWoodN1, ypred=Ypred[, cname])

controlplot(bWoodN1pred, 3, 2, var2round = TRUE, pch=mypch, 
            main="MachineShop average prediction",
            lwd=mylwd)

png("MachineShop.png", width = 800, height = 600)
controlplot(bWoodN1pred, 3, 2, var2round = TRUE, pch=mypch, 
            main="MachineShop average prediction",
            lwd=mylwd)
dev.off()


load(paste0(odir, "/","bWoodN1_validann_ann_BFGS.RData"))
idxmin <- which.min(allsummary["RMSE", ])
cname <- names(idxmin)
bWoodN1pred <- cbind.data.frame(bWoodN1, ypred=Ypred[, cname])
controlplot(bWoodN1pred, 3, 2, var2round = TRUE, pch=mypch, main="validann average prediction",
            lwd=mylwd)

png("validann.png", width = 800, height = 600)
controlplot(bWoodN1pred, 3, 2, var2round = TRUE, pch=mypch, main="validann average prediction",
            lwd=mylwd)
dev.off()

load(paste0(odir, "/","bWoodN1_nnet_nnet_none.RData"))
idxmin <- which.min(allsummary["RMSE", ])
cname <- names(idxmin)
bWoodN1pred <- cbind.data.frame(bWoodN1, ypred=Ypred[, cname])
controlplot(bWoodN1pred, 3, 2, var2round = TRUE, pch=mypch, main="nnet average prediction",
            lwd=mylwd)

png("nnet.png", width = 800, height = 600)
controlplot(bWoodN1pred, 3, 2, var2round = TRUE, pch=mypch, main="nnet average prediction",
            lwd=mylwd)
dev.off()

load(paste0(odir, "/","bWoodN1_rminer_fit_none.RData"))
idxmin <- which.min(allsummary["RMSE", ])
cname <- names(idxmin)
bWoodN1pred <- cbind.data.frame(bWoodN1, ypred=Ypred[, cname])
controlplot(bWoodN1pred, 3, 2, var2round = TRUE, pch=mypch, main="rminer average prediction",
            lwd=mylwd)

png("rminer.png", width = 800, height = 600)
controlplot(bWoodN1pred, 3, 2, var2round = TRUE, pch=mypch, main="rminer average prediction",
            lwd=mylwd)
dev.off()

load(paste0(odir, "/","bWoodN1_nlsr_nlxb_none.RData"))
idxmin <- which.min(allsummary["RMSE", ])
cname <- names(idxmin)
bWoodN1pred <- cbind.data.frame(bWoodN1, ypred=Ypred[, cname])
controlplot(bWoodN1pred, 3, 2, var2round = TRUE, pch=mypch, main="nlsr",
            lwd=mylwd)

png("nlsr.png", width = 800, height = 600)
controlplot(bWoodN1pred, 3, 2, var2round = TRUE, pch=mypch, main="nlsr",
            lwd=mylwd)
dev.off()
```

